services:
  backend:
    build: ./backend
    container_name: backend_django
    ports:
      - "8000:8000" # Use default django port
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    container_name: frontend_vue
    ports:
      - "5173:5173" # Use vite default port
    volumes:
      - ./frontend:/app # Mount for live changes
      - /app/node_modules # Avoid overwriting node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 # Run Vue dev server
    depends_on:
      - backend
